# Default values for chart-simple-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: bhargavshah86
  name: kube-test
  tag: v0.1

service:
  port: 80
  nodePort: 30080

resources: 
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi

secret:
  enabled: false
  username: "dead_duck"
  password: "my password dead duck ;)"

configmap:
  enabled: true
  filename: "config.ini"

volume:
  mountPath: "/usr/share/nginx/html"
