{{- if .Values.configmap.enabled }}
apiVersion: v1
data:
  config.ini: |-
{{ .Files.Get (printf "files/%s" .Values.configmap.filename) | indent 4 }}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
{{- end }}
