{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.secret.username }}
  password: {{ .Values.secret.password }}
{{- end }}
